### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ww102111** [bluebreezecf/SparkJobServerClient#11]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at org.khaleesi.carfield.tools.sparkjobserver.api.SparkJobServerClientFactory.<clinit>(SparkJobServerClientFactory.java:21)
	at SparkJobServerClientTest.SparkJobServerClientTest.main(SparkJobServerClientTest.java:28)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

**Comment by bluebreezecf** [comment]
@ww102111  this probelm doesn't occur in my environment, could you tell me how do you use sparkjobserverclient?

**Comment by bluebreezecf** [comment]
@ww102111 It seams that your run time environment has no jar of log4j.
Please try again.
