### ISSUE TITLE
Sometimes a NullPointer occurs while getting of the job

### ISSUE THREAD

**Issue by acommuni** [bluebreezecf/SparkJobServerClient#24]
There is sometimes an  error while getting job status : 

2018-05-18 08:29:46,557 [pool-5-thread-1] ERROR [com.bluebreezecf.tools.sparkjobserver.api.SparkJobServerClientImpl] - Error occurs when trying to get information of the target job:
 java.lang.NullPointerException
	at com.bluebreezecf.tools.sparkjobserver.api.SparkJobServerClientImpl.parseResult(SparkJobServerClientImpl.java:577)
	at com.bluebreezecf.tools.sparkjobserver.api.SparkJobServerClientImpl.getJobResult(SparkJobServerClientImpl.java:393)
	at com.erable.docker.SparkSimpleTest.runJob(SparkSimpleTest.java:114)
	at com.erable.docker.SparkSimpleTest.runAction(SparkSimpleTest.java:84)
	at com.erable.docker.SparkSimpleTest.lambda$test1UploadJar$0(SparkSimpleTest.java:77)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$2(AssertTimeout.java:100)
	at org.junit.jupiter.api.AssertTimeout.lambda$assertTimeoutPreemptively$4(AssertTimeout.java:134)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

Here is the final result from JobServer. There must be a transient satet where the result is not filled.

{
  "duration": "0.01 secs",
  "classPath": "com.orange.erable.spark.SimpleSparkJob",
  "startTime": "2018-05-18T07:15:40.148Z",
  "context": "SimpleSparkJobContext",
  "result": "Test OK",
  "status": "FINISHED",
  "jobId": "ac7eda52-023c-464b-b07f-dd02d3203d61"
}

Version of JobServer : 0.6.2

**Comment by knvs97** [comment]
Fixed in merge request #33 #28
